### ISSUE TITLE
Cannot reuse the same name for a deleted file

### ISSUE THREAD

**Issue by tsg** [elastic/filebeat#93]
The system test `test_crawler.py:Test.test_file_disappear_appear` fails on Windows and it is currently skipped. I've looked into it and seems that the test fails for a valid reason.

Here is the problematic situation:

 * Filebeat has a log file opened
 * Another application deletes the log file (e.g. for log rotation). This is allowed by Filebeat because it opens it with the share-delete option.
 * The file is deleted but still shows up in the filesystem until all other applications close it. In our case, Filebeat still has the file opened (a harvester for it is still running).
 * While in this deleted-but-not-quite state, calling stat on the file returns errors and, more importantly, another file with the same name cannot be created.

The test tries to create a file with the same name, so that fails. I'm afraid this situation can appear in common log rotation strategies, therefore the beta4 label.

**Comment by urso** [comment]
Would creating (should be supported by NTFS) hard links for log rotates files help. Using hard links we can link the file into a temporary folder and scan until original file is gone.

**Comment by tsg** [comment]
Posting what I tried already here because I feel stuck. Warning, pretty raw thoughts ahead.

I tried the following two ideas:

* Replace `h.file.Stat()` with `os.Stat(h.file.Name())` [here](https://github.com/elastic/filebeat/blob/master/harvester/log.go#L219). The idea is that in the situation described above the first one still returns something while the second one returns an error. In case of errors in this point, the Harverster releases the file which is what we want. This makes the test work on Windows, but the same test fails/becomes flaky on Unix.

* In the same place, leave the `h.file.Stat()` but add also a second call to `os.Stat()` so we check the result from both and compare. I.e.:

<pre>
@@ -213,6 +213,7 @@ func lineEndingChars(line []byte) int {

 // Handles error during reading file. If EOF and nothing special, exit without errors
 func (h *Harvester) handleReadlineError(lastTimeRead time.Time, err error) error {
        if err == io.EOF {
                // timed out waiting for data, got eof.
                // Check to see if the file was truncated
@@ -224,6 +225,15 @@ func (h *Harvester) handleReadlineError(lastTimeRead time.Time, err error) error
                        return statErr
                }

+               // On Windows, if h.File.Stat() succeeds and os.Stat() fails on the
+               // same file name, it usually means that the file was removed but it is
+               // still open by us. Make sure we return an error so that the file is
+               // closed.
+               if _, osStatErr := os.Stat(h.file.Name()); osStatErr != nil {
+                       logp.Err("File dissapeared from the FS, assuming error: %v", osStatErr)
+                       return fmt.Errorf("os.Stat() error on %s: %v", h.Path, osStatErr)
+               }
+
                if h.ProspectorConfig.IgnoreOlder != "" {
                        logp.Debug("harvester", "Ignore Unmodified After: %s", h.ProspectorConfig.IgnoreOld
                }
</pre>

This second solution seems to work on both Windows and Unix but it takes up to 10 seconds for the Harvester to notice that the file is gone, because of the hard-coded timeout [here](https://github.com/elastic/filebeat/blob/master/harvester/log.go#L41). If I make that 1 second instead of 10, the test passes and the file is released within one second (good enough?) but than the renaming test fails. So I got stuck with this one as well. 

I could try to do different things on Win/Non-Win or to further complicate the logic to list the directory above, etc, but it feels like going down a rabbit hole. Maybe trying to detect this condition in the prospector rather than in the harvester would have better chances of getting things just right, but at the moment the prospector cannot tell the harversters to shut down so that would have to be implemented.

I'm only trying these things to have a somehow-working short term solution (i.e. at least don't keep the files opened/blocked forever). But it looks like any solution based on polling will be at least for a while susceptible to the problem above.

For a more long term/clean solution I think using [fsnotify](https://github.com/go-fsnotify/fsnotify) for reliably detecting what happens on the system and only use polling for network drives when there's no other chance is the way go.

@urso's proposed solution might work, but it's also in the long-term category and we need to support fat32 as well.

**Comment by mikemccand** [comment]
FWIW Lucene also struggles with this sneaky "pending delete" that a file can be in, on Windows, where it was deleted yet the file handle is still held open by another process or thread, and it shows up in directory listings, but you cannot do anything with that filename nor overwrite it.

Dealing with this Windows only "difficulty" was the motivation for this new Lucene issue: https://issues.apache.org/jira/browse/LUCENE-6835

**Comment by tsg** [comment]
Thanks @mikemccand, I'll look there for inspiration. Also, confirmation that this Windows "difficulty" is annoying also to smarter minds makes me feel better :-).

**Comment by ruflin** [comment]
@tsg I'm having a look at this now again. I'm thinking of going with the implementation you tried first but have a function in file which is platform specific. So we don't slow down or change the unix behaviour but make it work under windows.

**Comment by tsg** [comment]
+1, sounds good.

**Comment by ruflin** [comment]
Wasn't successful yet in finding a good solution.
Good post on the topic from @driskell https://github.com/driskell/log-courier/issues/119

**Comment by ruflin** [comment]
This issue is fixed through configuration here: https://github.com/elastic/filebeat/pull/146

**Comment by ruflin** [comment]
Closing as https://github.com/elastic/filebeat/pull/146 was merged.

**Comment by lhm** [comment]
@ruflin I'm still having problems with this. The server I'm monitoring rotates its logfiles on startup by renaming `server.log` to `server.lo#`. I have `force_close_windows_files` set to `true` in the filebeat config. After a server restart, filebeat appears to have a handle on the rotated file (according to [sysinternals handle.exe](https://technet.microsoft.com/de-de/sysinternals/handle)). That is being released after `ignore_older` time has elapsed. The way I understand the docs for the force_close_windows_files option, the rotated file should have been closed immediately on the rename.
A workaround would be to set ignore_older to a very short time span, but the server has some idle time, and thus legitimate new loglines would be ignored.
I'm using Windows Server 2012 R2, and filebeat-nightly.151104212559-windows.

Should I open a new issue for this?

**Comment by ruflin** [comment]
@lhm Based on what you describe above, it sounds like after a restart filebeat will open the file again. What confuses me that I assume after the restart, the specific file does not even exist? What do you exactly mean by the server restart?

What ist the order of:
* File renaming
* Creating new file
* Restarting server
* Starting filebeat again?

I suggest we keep the discussion here for the moment and open a new one as soon as we figured out where the issue is.

**Comment by lhm** [comment]
@ruflin Sorry if I wasn't clear, I'll try answer your questions and explain this a bit more structured. By "server restart" I mean restarting the server which is producing the logs I want to ship with filebeat. The server rotates its logs a) when (re-)started or b) based on logfile size when running.

When rotating the log file:
1. It deletes the file `server.lo#` if exists
2. Renames the previous logfile `server.log` to `server.lo#`
3. Creates `server.log` and start writing logs to that file

I have filebeat configured to ship logs from the `server.log` file to logstash. When the server process is being restarted while filebeat is running, I run into problems at step 1 above, because filebeat has an open file handle on the rotated `server.lo#` file, which prevents it from being deleted cleanly. I think this is unrelated to access rights and share_mode, but a windows-specific problem, described also [here](https://boostgsoc13.github.io/boost.afio/doc/html/afio/FAQ/deleting_open_files.html). The file handle is being closed after the time configured in `ignore_older`, but I have that set to a rather high value, and is not a good workaround.

My understanding of the `force_close_windows_files` config option is that it should make filebeat close the monitored logfile immediately as it is being renamed. Thus, the situation described should not occur, because filebeat would simply never have a handle on a file named `server.lo#`. 

The described scheme is arguably not the best way to handle log rotation, but I still think that the `force_close_windows_files` is not working exactly as expected. 

Does that clear up the issue a bit? Thanks for looking into this!

**Comment by ruflin** [comment]
@lhm Thanks for the explanation, that clarifies the question. I will try to reproduce it as this is exactly what `force_close_windows_files` should solve. 

Does the issue only occur on restart (case a) or also when log is rotated because of file size (case b)? The reason I'm asking because perhaps "somehow" the unique file identifier changes and after rotation filebeat actually closes the wrong file handler. Are the files on a shared disk?

I reopened the issue so we keep an eye on this one.

**Comment by lhm** [comment]
@ruflin It also happens when the log is rotated by size. The files are not on a shared disk, but I'm currently testing this from within a Virtualbox VM using Vagrant.

**Comment by ruflin** [comment]
@lhm Looking into the issue I found a potential problem when the rotation happens under high load (or bad timing) which leads to not starting the file from beginning as it is not properly closed. Perhaps this also relates to this issue. 

Just curious: Are you using any of the public available vagrant boxes?

**Comment by lhm** [comment]
@ruflin No, unfortunately these are custom build. I'll see if I can make this reproducible with a public available box.

**Comment by ruflin** [comment]
@lhm No worries. I don't assume it is the box. Here is the box we are using: https://github.com/elastic/filebeat/blob/master/Vagrantfile

**Comment by lhm** [comment]
@ruflin Nice, hadn't seen that before - I'll give it a go tomorrow. In the meantime I came up with this horrible powershell script, that reproduces the issue I'm seeing: https://gist.github.com/lhm/ab3d686d15cd41196b74
I also put some output from Handle.exe there, showing the file handles being held.

**Comment by ruflin** [comment]
@lhm Thanks a lot for the gist. Will take a closer look.
The reason I was asking for you VirtualBox setup is because ours is far from perfect.

**Comment by ruflin** [comment]
@lhm We incorporated quite a few fixes in the last few days. It would be nice if you could try again with the latest nightlies: https://beats-nightlies.s3.amazonaws.com/index.html?prefix=filebeat/ Be aware that the `force_close_windows_files` was renamed to `force_close_files` as it works now on all platforms.

**Comment by lhm** [comment]
@ruflin I just tried it with the 1.0.0 version, but unfortunately it doesn't fix my problem. I'm still seeing filebeat.exe having a handle to the rotated file, which prevents it from being deleted.

**Comment by ruflin** [comment]
@lhm Thanks for reporting. Looks like we need to have a deeper look here again on what is going on. Does it report in the log file that the file was closed (but actually it isn't)? I still need to test your gist you provided above to reproduce the error.

**Comment by lhm** [comment]
@ruflin I can't find anything in the logfile regarding closing files: https://gist.github.com/lhm/ab3d686d15cd41196b74#file-004-filebeat-log
I started filebeat with `C:\filebeat\filebeat.exe -c .\filebeat.yml -v -d "*"`
The log has two runs of the logproducer scripts, you can see where the producer was started when filebeat starts shipping the events. The rename of the logfile should happen directly before that.

**Comment by ruflin** [comment]
@lhm Strangely I would also expect to see some EOF read errors as it seems to have reached the end of the file: https://gist.github.com/lhm/ab3d686d15cd41196b74#file-004-filebeat-log-L142

**Comment by ruflin** [comment]
@lhm To make sure we know if the files reached EOF and were closed, I improved the logging with this PR here: https://github.com/elastic/filebeat/pull/294 As soon as it is merged I will build the nightlies so we can try the most recent version if that is ok for?

**Comment by ruflin** [comment]
@lhm I now triggered the nightly builds and it should be available here soonish: https://beats-nightlies.s3.amazonaws.com/index.html?prefix=filebeat/

**Comment by lhm** [comment]
@ruflin I've run the test script with the latest nightly, there is more infos in the logs now I believe: https://gist.github.com/lhm/ab3d686d15cd41196b74#file-filebeat-nightly-151127-log
It shows infos about rotated file, but nothing about force closing the old one, unfortunately.

**Comment by ruflin** [comment]
@lhm I think the new log file gives me some indications on what happens. Here my assumption:
* To decide that a file was rotate and should be closed, it is checked if the file can still be read based on the file name: https://github.com/elastic/filebeat/blob/master/harvester/log.go#L276
* In your case, if that is tried, already a new file under the name exists, so this does not raise an error

We recently changed the order of this check which seems to lead to the problem, that it is not fast enough anymore (or never was). A potential solution here is to not only check for an error but also if the file stats actually identically or not. I will try to add this additional check and let you know, as soon as it is implemented.

**Comment by ruflin** [comment]
@lhm I hope that this one finally solves the issue: https://github.com/elastic/filebeat/pull/302 I started the build for the nightlies again and a new one should be available soonish.

**Comment by lhm** [comment]
@ruflin: That fixed it! I tested it with the 151202-nightly, and there are no errors, both with the test script and the real server. The logfile now includes "force close" messages: https://gist.github.com/lhm/ab3d686d15cd41196b74#file-filebeat-nightly-151202-log

Thanks a lot for taking the time for looking into this!

**Comment by ruflin** [comment]
@lhm That is great to hear. Sorry it took so long to figure out what is going on, but I'm happy it works now. It will be part of the next release. I will close this issue. Please reopen it again, in case the issue appears again.
